### ISSUE TITLE
Figure out a way to rustfmt Serkr

### ISSUE THREAD

**Issue by mAarnos** [mAarnos/Serkr#6]
Currently we are blocked by the fact that rustfmt completely demolishes formatting in string literals due to significant spacing, e.g. the code

     println!("forall x. forall y. forall z. mult(x, mult(y, z)) = mult(mult(x, y), z) /\\
     forall x. mult(e(), x) = x /\\
     forall x. mult(x, x) = e()
     ==> forall x. forall y. mult(x, y) = mult(y, x)");

gets formatted to

     println!("forall x. forall y. forall z. mult(x, mult(y, z)) = mult(mult(x, y), z) /\forall \
     x. mult(e(), x) = x /\forall x. mult(x, x) = e()
     ==> forall x. \
     forall y. mult(x, y) = mult(y, x)");

which is pretty horrible.

**Comment by Ticki** [comment]
Well, rustfmt is configurable, so this should be quite easy. Just set `max_line_length` to something really large.

**Comment by mAarnos** [comment]
This is now done, see #13.

**Comment by Ticki** [comment]
Nice! And great work, you're doing!

**Comment by mAarnos** [comment]
Thanks. Not as great work as you are doing however. I might some day start contributing to Redox as well, since there are lots of opportunities to use formal methods.
